const policySearchKeywords: { [key: string]: string } = {
  "Ayushman Bharat Pradhan Mantri Jan Arogya Yojana (AB-PMJAY)": "Ayushman Bharat",
  "Pradhan Mantri Matru Vandana Yojana (PMMVY)": "PMMVY",
  "National Health Mission (NHM)": "National Health Mission",
  "Poshan Abhiyaan": "Poshan Abhiyaan",
  "Mission Indradhanush": "Mission Indradhanush",
  "Pradhan Mantri Awas Yojana (PMAY)": "PMAY",
  "Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA)": "MGNREGA",
  "Pradhan Mantri Gram Sadak Yojana (PMGSY)": "PMGSY",
  "Deendayal Antyodaya Yojana (DAY-NRLM)": "DAY NRLM",
  "Swachh Bharat Mission (SBM)": "Swachh Bharat",
  "Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)": "PM Kisan",
  "Pradhan Mantri Fasal Bima Yojana (PMFBY)": "PMFBY",
  "Kisan Credit Card (KCC)": "Kisan Credit Card",
  "Soil Health Card Scheme": "Soil Health Card",
  "e-NAM (National Agricultural Market)": "e-NAM",
  "Samagra Shiksha Abhiyan": "Samagra Shiksha",
  "Mid-Day Meal Scheme": "Mid Day Meal",
  "Pradhan Mantri Vidya Lakshmi Karyakram (PMVLK)": "Vidya Lakshmi",
  "Skill India Mission": "Skill India",
  "National Apprenticeship Promotion Scheme (NAPS)": "NAPS",
  "Beti Bachao Beti Padhao (BBBP)": "Beti Bachao Beti Padhao",
  "Sukanya Samriddhi Yojana (SSY)": "Sukanya Samriddhi",
  "Ujjwala Yojana": "Ujjwala Yojana",
  "One Stop Centre (OSC) Scheme": "One Stop Centre Scheme",
  "Pradhan Mantri Jan Dhan Yojana (PMJDY)": "Jan Dhan Yojana",
  "Atal Pension Yojana (APY)": "Atal Pension Yojana",
  "Pradhan Mantri Suraksha Bima Yojana (PMSBY)": "PMSBY",
  "Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)": "PMJJBY",
  "Smart Cities Mission": "Smart Cities Mission",
  "BharatNet": "BharatNet",
  "Pradhan Mantri Gramin Digital Saksharta Abhiyan (PMGDISHA)": "PMGDISHA",
  "Startup India": "Startup India",
  "Stand-Up India": "Stand Up India",
  "MUDRA Yojana": "MUDRA Yojana",
  "National Social Assistance Programme (NSAP)": "NSAP",
  "Atal Mission for Rejuvenation and Urban Transformation (AMRUT)": "AMRUT",
  "Pradhan Mantri Kaushal Vikas Yojana (PMKVY)": "PMKVY",
  "Deen Dayal Upadhyaya Grameen Kaushalya Yojana (DDU-GKY)": "DDU GKY",
  "National Career Service (NCS)": "National Career Service",
  "Rashtriya Krishi Vikas Yojana (RKVY)": "RKVY",
  "Pradhan Mantri Krishi Sinchayee Yojana (PMKSY)": "PMKSY",
  "PM SHRI Schools": "PM SHRI Schools",
  "National Means-cum-Merit Scholarship Scheme (NMMSS)": "NMMSS",
  "Mahila Shakti Kendra": "Mahila Shakti Kendra",
  "Swadhar Greh Scheme": "Swadhar Greh",
  "Ujjawala Scheme": "Ujjawala Scheme"
};

export default policySearchKeywords; 