const policies = [
  "Ayushman Bharat Pradhan Mantri Jan Arogya Yojana (AB-PMJAY)",
  "Pradhan Mantri Matru Vandana Yojana (PMMVY)",
  "National Health Mission (NHM)",
  "Poshan Abhiyaan",
  "Mission Indradhanush",
  "Pradhan Mantri Awas Yojana (PMAY)",
  "Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA)",
  "Pradhan Mantri Gram Sadak Yojana (PMGSY)",
  "Deendayal Antyodaya Yojana (DAY-NRLM)",
  "Swachh Bharat Mission (SBM)",
  "Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)",
  "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
  "Kisan Credit Card (KCC)",
  "Soil Health Card Scheme",
  "e-NAM (National Agricultural Market)",
  "Samagra Shiksha Abhiyan",
  "Mid-Day Meal Scheme",
  "Pradhan Mantri Vidya Lakshmi Karyakram (PMVLK)",
  "Skill India Mission",
  "National Apprenticeship Promotion Scheme (NAPS)",
  "Beti Bachao Beti Padhao (BBBP)",
  "Sukanya Samriddhi Yojana (SSY)",
  "Ujjwala Yojana",
  "One Stop Centre (OSC) Scheme",
  "Pradhan Mantri Jan Dhan Yojana (PMJDY)",
  "Atal Pension Yojana (APY)",
  "Pradhan Mantri Suraksha Bima Yojana (PMSBY)",
  "Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)",
  "Smart Cities Mission",
  "BharatNet",
  "Pradhan Mantri Gramin Digital Saksharta Abhiyan (PMGDISHA)",
  "Startup India",
  "Stand-Up India",
  "MUDRA Yojana",
  "National Social Assistance Programme (NSAP)",
  "Atal Mission for Rejuvenation and Urban Transformation (AMRUT)",
  "Pradhan Mantri Kaushal Vikas Yojana (PMKVY)",
  "Deen Dayal Upadhyaya Grameen Kaushalya Yojana (DDU-GKY)",
  "National Career Service (NCS)",
  "Rashtriya Krishi Vikas Yojana (RKVY)",
  "Pradhan Mantri Krishi Sinchayee Yojana (PMKSY)",
  "PM SHRI Schools",
  "National Means-cum-Merit Scholarship Scheme (NMMSS)",
  "Mahila Shakti Kendra",
  "Swadhar Greh Scheme",
  "Ujjawala Scheme"
];

export default policies;